// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DByQv_yAK4_T2WHnUijs356S0mrzeiY',
    appId: '1:962322866343:web:6aaf30f3c551caac983b82',
    messagingSenderId: '962322866343',
    projectId: 'self-care-bed47',
    authDomain: 'self-care-bed47.firebaseapp.com',
    storageBucket: 'self-care-bed47.appspot.com',
    measurementId: 'G-0FBH1PX1RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMJv4sP5l37z5i-1eNaylXqPTKB3f8cQ',
    appId: '1:962322866343:android:eaf9dfb362d189de983b82',
    messagingSenderId: '962322866343',
    projectId: 'self-care-bed47',
    storageBucket: 'self-care-bed47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Cx0Oi--5LsVovMwMpYUSwM90oyCeQCg',
    appId: '1:962322866343:ios:0a73054c5e656900983b82',
    messagingSenderId: '962322866343',
    projectId: 'self-care-bed47',
    storageBucket: 'self-care-bed47.appspot.com',
    iosClientId: '962322866343-b3n42bk99jrkgsun03l88qus77qk2f28.apps.googleusercontent.com',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Cx0Oi--5LsVovMwMpYUSwM90oyCeQCg',
    appId: '1:962322866343:ios:0a73054c5e656900983b82',
    messagingSenderId: '962322866343',
    projectId: 'self-care-bed47',
    storageBucket: 'self-care-bed47.appspot.com',
    iosClientId: '962322866343-b3n42bk99jrkgsun03l88qus77qk2f28.apps.googleusercontent.com',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8DByQv_yAK4_T2WHnUijs356S0mrzeiY',
    appId: '1:962322866343:web:e91bd887a7d997a5983b82',
    messagingSenderId: '962322866343',
    projectId: 'self-care-bed47',
    authDomain: 'self-care-bed47.firebaseapp.com',
    storageBucket: 'self-care-bed47.appspot.com',
    measurementId: 'G-BVHQBPQF4L',
  );
}
